using System;
using System.Collections.Generic;
using System.Text;

namespace Grayeed
{
    public class GrayedInfo
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public string Calling { get; set; }
        public string Email { get; set; }
        public string WebsiteLink { get; set; }
        public string FacebookLink { get; set; }
        public string TwitterLink { get; set; }
        public string YoutubeLink { get; set; }
        public string GPlusLink { get; set; }
        public string LinkedInLink { get; set; }
        public string InstagramLink { get; set; }
        public string Long { get; set; }
        public string Lat { get; set; }
    }
    public class Data
    {
        public List<GrayedInfo> GrayedData { get; set; }
        public void Data_in ()
        {
            //GrayedData.Add(new GrayedInfo() { Name = "", Image = "Assets/", Calling = "",Email="", WebsiteLink = "", FacebookLink = "", TwitterLink = "", YoutubeLink = "", GPlusLink = "", LinkedInLink = "",InstagramLink="", Long = , Lat = });
            GrayedData = new List<GrayedInfo>();
            GrayedData.Add(new GrayedInfo() { ID = 0, Name = "الأهرام", Image = "Assets/Ahram.png", Calling = "27704444", WebsiteLink = "http://www.ahram.org.eg/", FacebookLink = "https://www.facebook.com/Alahram.Newspaper", TwitterLink = "https://twitter.com/eahram", YoutubeLink = "http://www.youtube.com/AhramGate", GPlusLink = "https://plus.google.com/u/0/100709128407881054018/posts", LinkedInLink = "http://www.linkedin.com/company/540680?trk=cws-btn-overview-0-0", Lat = "31.239301999999952", Long = "30.055662 " });
            GrayedData.Add(new GrayedInfo() { ID = 1, Name = "أخبار اليوم", Image = "Assets/AkhbarElYoum.png", Calling = "0225807113", WebsiteLink = "http://akhbarelyom.com/", FacebookLink = "https://www.facebook.com/Alakhbargate", TwitterLink = "https://twitter.com/akhbarelyom_eg", YoutubeLink = "https://www.youtube.com/user/akhbarelyoumtv", GPlusLink = "https://plus.google.com/u/0/+akhbarelyoum/posts", Lat = "31.237777999999935", Long = "30.055565" });
            GrayedData.Add(new GrayedInfo() { ID = 2, Name = "الجمهورية", Image = "Assets/Aljomhoria.png", Calling = "02 23923749", Email = "eltahrir@eltahrir.net", WebsiteLink = "http://www.algomhuria.net.eg/algomhuria/today/fpage/", FacebookLink = "http://www.facebook.com/AlGomhuria.Newspaper", TwitterLink = "https://twitter.com/algomhuria", YoutubeLink = "https://www.youtube.com/user/algomhoria1", Lat = "31.24003700000003", Long = "30.04801" });
            GrayedData.Add(new GrayedInfo() { ID = 3, Name = "الوفد", Image = "Assets/Alwafd.png", Calling = "33383222", WebsiteLink = "http://www.alwafd.org", FacebookLink = "https://www.facebook.com/alwafdportal?fref=ts", TwitterLink = "https://twitter.com/alwafdportal", YoutubeLink = "https://www.youtube.com/user/wafdvideo", GPlusLink = "https://plus.google.com/+%D8%A7%D9%84%D9%88%D9%81%D8%AF", Lat = "31.214699999999993", Long = "30.0409" });
            GrayedData.Add(new GrayedInfo() { ID = 4, Name = "الشروق", Image = "Assets/AlShrouk.png", Calling = "02279303040", Email = "contactus@shorouknews.com", WebsiteLink = "http://www.shorouknews.com/", FacebookLink = "https://www.facebook.com/shorouknews", TwitterLink = "https://twitter.com/shorouk_news", YoutubeLink = "https://www.youtube.com/user/ShoroukVideos", GPlusLink = "https://plus.google.com/115129833770808747847/posts", Lat = "31.208262999999988", Long = "30.051236" });
            GrayedData.Add(new GrayedInfo() { ID = 5, Name = "رصد الإخبارية", Image = "Assets/Rasd.png", WebsiteLink = "http://rassd.com/", FacebookLink = "https://www.facebook.com/RassdNewsN", TwitterLink = "https://twitter.com/RassdNewsN", YoutubeLink = "https://www.youtube.com/RassdNewsN", GPlusLink = "https://plus.google.com/+RassdNewsN/videos" });
            GrayedData.Add(new GrayedInfo() { ID = 6, Name = "اليوم السابع", Image = "Assets/AlyoumAlsabee.png", Calling = "02 37612697", WebsiteLink = "http://www.youm7.com/", FacebookLink = "https://www.facebook.com/Youm7", TwitterLink = "https://twitter.com/youm7", YoutubeLink = "https://www.youtube.com/user/mubasheryoum7", GPlusLink = "https://plus.google.com/+Youm7/posts", InstagramLink = "Instagram: https://instagram.com/youm7newspaper/", Lat = "31.204735000000028", Long = "30.052605" });
            GrayedData.Add(new GrayedInfo() { ID = 7, Name = "المصرى اليوم", Image = "Assets/AlmasryAlyoum.png", Calling = "27980100", WebsiteLink = "http://www.almasryalyoum.com/", FacebookLink = "https://www.facebook.com/almasryalyoum", TwitterLink = "https://twitter.com/AlMasryAlYoum", GPlusLink = "https://plus.google.com/+almasryalyoum/posts", Lat = "31.232500000000073", Long = "30.0369" });
            GrayedData.Add(new GrayedInfo() { ID = 8, Name = "الوطن", Image = "Assets/AlWatn.png", Calling = "02 33331000", Email = "info@elwatannews.com", WebsiteLink = "http://www.elwatannews.com/", FacebookLink = "https://www.facebook.com/ElWatanNews", TwitterLink = "https://twitter.com/elwatannews", Lat = "31.208258999999998", Long = "30.0379482" });
            GrayedData.Add(new GrayedInfo() { ID = 9, Name = "شعب مصر", Image = "Assets/Sha3bMasr.png", Calling = "02 27949407", Email = "info@egyptianpeople.com", WebsiteLink = "http://egyptianpeople.com/", FacebookLink = "https://www.facebook.com/egyptianpeoplenews", TwitterLink = "https://twitter.com/sh3bmasr", YoutubeLink = "https://www.youtube.com/user/sh3bmasrchannel", GPlusLink = "https://plus.google.com/102924286919656817594/posts", Lat = "31.23786700000005", Long = "30.03865" });
            GrayedData.Add(new GrayedInfo() { ID = 10, Name = "بوابة فيتو", Image = "Assets/Veto.png", Calling = "33382266", Email = "info@vetogate.com", WebsiteLink = "http://www.vetogate.com/", FacebookLink = "https://www.facebook.com/Vetogate", TwitterLink = "https://twitter.com/Vetogate", YoutubeLink = "https://www.youtube.com/user/VetogateOfficial", GPlusLink = "https://plus.google.com/+Vetogatepage/videos", Long = "30.009933", Lat = "31.217789" });
            GrayedData.Add(new GrayedInfo() { ID = 11, Name = "المُوجز", Image = "Assets/Almogaz.png", Email = "almogaz@orangestudio.com", WebsiteLink = "http://almogaz.com/", FacebookLink = "https://www.facebook.com/AlmogazNews", TwitterLink = "https://twitter.com/Almogaz", GPlusLink = "https://plus.google.com/+Almogaz", Long = "30.037724", Lat = "31.23695399999997" });
            GrayedData.Add(new GrayedInfo() { ID = 12, Name = "المصريون", Image = "Assets/AlMasrion.png", Calling = "01069090805", Email = "almesryoon.newspaper@gmail.com  ", WebsiteLink = "http://almesryoon.com/", FacebookLink = "https://www.facebook.com/pages/%D8%A7%D9%84%D9%85%D8%B5%D8%B1%D9%8A%D9%88%D9%86-Almesryoon/727458410636817", TwitterLink = "https://twitter.com/almesryoonnews", Lat = "31.30319600000007", Long = "30.073928" });
            GrayedData.Add(new GrayedInfo() { ID = 13, Name = "البوابة نيوز", Image = "Assets/AlbwabaNews.png", Calling = "0020233389640", Email = "albawabhnews@gmail.com", WebsiteLink = "http://www.albawabhnews.com/", FacebookLink = "https://www.facebook.com/Albawaba.eg", TwitterLink = "https://twitter.com/AlBawabaNews", YoutubeLink = "https://www.youtube.com/channel/UCU0s_Dr2oPn6TGz25cj205w", GPlusLink = "https://plus.google.com/+Albawabanews1", Long = "30.039261", Lat = "31.204140" });
            GrayedData.Add(new GrayedInfo() { ID = 14, Name = "بوابة الفجر", Image = "Assets/Alfagr.png", Calling = "(023)336-6164", Email = "info@elfagr.org", WebsiteLink = "http://www.elfagr.org/", FacebookLink = "https://www.facebook.com/Elfagr.org", TwitterLink = "https://twitter.com/ElfagrNews", YoutubeLink = "https://www.youtube.com/user/VideoElfagr", GPlusLink = "https://plus.google.com/109848750329937369913", Lat = "31.20744000000002", Long = "30.054323" });
            GrayedData.Add(new GrayedInfo() { ID = 15, Name = "المُحيط", Image = "Assets/Moheet.png", Calling = "0100 9593 800", Email = "basyony@moheet.com", WebsiteLink = "http://www.moheet.com/", FacebookLink = "https://www.facebook.com/MoheetNews", YoutubeLink = "https://www.youtube.com/user/MoheetTV", GPlusLink = "https://plus.google.com/+moheet" });
            GrayedData.Add(new GrayedInfo() { ID = 16, Name = "وكالة أنباء ONA", Image = "Assets/Ona.png", Calling = "+20273722024", WebsiteLink = "http://onaeg.com/", FacebookLink = "https://www.facebook.com/ONAeg", TwitterLink = "https://twitter.com/onewsagency", YoutubeLink = "https://www.youtube.com/user/onaeg", Long = "30.070785", Lat = "31.219818" });
            GrayedData.Add(new GrayedInfo() { ID = 17, Name = "الدستور", Image = "Assets/AlDostor.png", WebsiteLink = "http://www.dostor.org/", FacebookLink = "https://www.facebook.com/aldostornews", TwitterLink = "https://twitter.com/aldostornews", YoutubeLink = "https://www.youtube.com/user/aldostornews", Lat = "31.217223999999987", Long = "30.029573" });
            GrayedData.Add(new GrayedInfo() { ID = 18, Name = "التحرير", Image = "Assets/AlTahrir.png", WebsiteLink = "http://www.tahrirnews.com/news/", FacebookLink = "https://www.facebook.com/Tahrir.News.Official", TwitterLink = "https://twitter.com/tahrir_news", YoutubeLink = "https://www.youtube.com/channel/UCI9WkHoYhyOmP8EuFa8oKYw", GPlusLink = "https://plus.google.com/+TahrirnewsOfficial/posts", InstagramLink = "http://instagram.com/tahrirnews", Long = "30.052823", Lat = "31.194414" });
            GrayedData.Add(new GrayedInfo() { ID = 19, Name = "مصر اليوم", Image = "Assets/MasrAlyom.png", Calling = "01287800872", Email = "info@egypttoday.co.uk", WebsiteLink = "http://www.egypttoday.co.uk/", FacebookLink = "https://www.facebook.com/Egypttoday.co.uk", TwitterLink = "https://twitter.com/egyptiontoday", YoutubeLink = "https://www.youtube.com/user/Egypttodaytv/", GPlusLink = "https://plus.google.com/116238258877384834643/posts", Long = "30.085557", Lat = "31.245407" });
            GrayedData.Add(new GrayedInfo() { ID = 20, Name = "مصر فايف", Image = "Assets/MasrFive.png", Calling = "01060052651", Email = "info@misr5.com", WebsiteLink = "http://www.misr5.com/", FacebookLink = "https://www.facebook.com/misr5.official", TwitterLink = "https://twitter.com/Misr5official", YoutubeLink = "https://www.youtube.com/user/misr5official", GPlusLink = "https://plus.google.com/+Misr5" });
            GrayedData.Add(new GrayedInfo() { ID = 21, Name = "القاهرة الإخبارية", Image = "Assets/AlQahiraAlyom.png", WebsiteLink = "http://www.cairoportal.com/", FacebookLink = "https://www.facebook.com/CairoNewsPortal", TwitterLink = "https://twitter.com/CairoNewsPortal", YoutubeLink = "https://www.youtube.com/channel/UCXYhTp-qTwsYpyDJxkjwJrQ", GPlusLink = "https://plus.google.com/+Cairoportalcairoportal", Lat = "31.25026600000001", Long = "30.063579" });
            GrayedData.Add(new GrayedInfo() { ID = 22, Name = "مصر العربية", Image = "Assets/MasrAlArbia.png", Calling = "0237605163", Email = "maqlat@masralarabia.com", WebsiteLink = "http://www.masralarabia.com/", FacebookLink = "https://www.facebook.com/masralarabiaofficial", TwitterLink = "https://twitter.com/masralarabia", YoutubeLink = "https://www.youtube.com/user/masralarbya?sub_confirmation=1", GPlusLink = "https://plus.google.com/+Masralarabia/posts", Long = "30.049658", Lat = "31.237611000000015" });
            GrayedData.Add(new GrayedInfo() { ID = 23, Name = "صدى البلد", Image = "Assets/SadaElBalad.png", Calling = "02-33380115", Email = "info@el-balad.com", WebsiteLink = "http://www.el-balad.com/", FacebookLink = "https://www.facebook.com/ElBaladOfficial", TwitterLink = "https://twitter.com/el_balad", YoutubeLink = "https://www.youtube.com/user/ElBaladOfficial", GPlusLink = "https://plus.google.com/u/0/108020183982337727100/posts", InstagramLink = "https://instagram.com/elbalad/", Lat = "31.207303000000024", Long = "30.051674" });
            GrayedData.Add(new GrayedInfo() { ID = 24, Name = "فيس مصر", Image = "Assets/FaceMasr.png", Calling = "23909079", Email = "INFO@FACE-MASR.COM", WebsiteLink = "http://www.face-masr.com/", FacebookLink = "https://www.facebook.com/FaceMasreg/timeline", TwitterLink = "https://twitter.com/FaceMasreg", YoutubeLink = "http://www.youtube.com/FaceMasreg", Long = "29.962696", Lat = "31.276941999999963" });
            GrayedData.Add(new GrayedInfo() { ID = 25, Name = "الشعب", Image = "Assets/AlShaab.png", Email = "info@elshaab.org", WebsiteLink = "http://www.elshaab.org/", FacebookLink = "https://www.facebook.com/elshaabnews", TwitterLink = "https://twitter.com/elshaabnews", YoutubeLink = "https://www.youtube.com/user/elshaabnews", GPlusLink = "https://plus.google.com/+ElshaabOrg1/", Long = "30.050084", Lat = "31.245183" });
            GrayedData.Add(new GrayedInfo() { ID = 26, Name = "النهار المصرية", Image = "Assets/AlNahar.png", Calling = "02-2792-6950", Email = "•mohaelbanna@gmail.com", WebsiteLink = "http://www.alnaharegypt.com/nhar/index.html", FacebookLink = "https://www.facebook.com/alnaharegypt", TwitterLink = "https://twitter.com/alnahar_egypt", YoutubeLink = "https://www.youtube.com/user/alnaharegypt1", GPlusLink = "https://plus.google.com/+Alnaharegypt/posts", Lat = "31.20224600000006", Long = "30.049885" });
            GrayedData.Add(new GrayedInfo() { ID = 27, Name = "الصباح العربى", Image = "Assets/AlSabahElAraby.png", Email = "info@sabaharabi.com", WebsiteLink = "http://www.sabaharabi.com/", FacebookLink = "https://www.facebook.com/AlsabahPress", TwitterLink = "https://twitter.com/AlsabahPress", GPlusLink = "https://plus.google.com/+Sabaharabipress" });
            GrayedData.Add(new GrayedInfo() { ID = 28, Name = "الوسط", Image = "Assets/AlWast.png", Email = "h@el-wasat.com", WebsiteLink = "http://www.el-wasat.com/portal/index.html", FacebookLink = "https://www.facebook.com/elwasatnewspaper", TwitterLink = "https://twitter.com/el_wasat", YoutubeLink = "https://www.youtube.com/user/elwasatnewspaper" });
            GrayedData.Add(new GrayedInfo() { ID = 29, Name = "البديل", Image = "Assets/AlBadil.png", Calling = "+202 27962240", Email = "•	Social@elbadil.com", WebsiteLink = "http://elbadil.com/", FacebookLink = "https://www.facebook.com/Elbadil", TwitterLink = "https://twitter.com/elbadilnews", YoutubeLink = "https://www.youtube.com/channel/UCz_svmiY2ordSwmX3pfyPvg", GPlusLink = "https://plus.google.com/+Elbadeil/posts" });
            GrayedData.Add(new GrayedInfo() { ID = 30, Name = "أخبارنا اليوم", Image = "Assets/AkhbarnaAlyom.png", Email = "cs@akhbarelyaom.com", WebsiteLink = "http://www.akhbrna.com/", FacebookLink = "https://www.facebook.com/akhbrnaalyoum", TwitterLink = "https://twitter.com/akhbrnaalyoum", GPlusLink = "https://plus.google.com/%23", Long = "30.101225", Lat = "31.36871599999995" });
            GrayedData.Add(new GrayedInfo() { ID = 31, Name = "أخبارك", Image = "Assets/Akhbark.png", Email = "webmaster@akhbarak.net", WebsiteLink = "http://beta.akhbarak.net/", FacebookLink = "https://www.facebook.com/Akhbarak.net", TwitterLink = "https://twitter.com/akhbarak_net", Long = "30.037413", Lat = "31.217093999999975" });
            GrayedData.Add(new GrayedInfo() { ID = 32, Name = "بوابة الأسبوع", Image = "Assets/bWABTaLoSBOO.PNG", Calling = "01000596841", Email = "elosboanews@yahoo.com", WebsiteLink = "http://www.elaosboa.com/", FacebookLink = "https://www.facebook.com/pages/%D8%A8%D9%88%D8%A7%D8%A8%D8%A9-%D8%A7%D9%84%D8%A7%D8%B3%D8%A8%D9%88%D8%B9/544791535566189", TwitterLink = "https://twitter.com/elosboanews", YoutubeLink = "https://www.youtube.com/channel/UCqbs-fzrDEdLC5YNxsT6zaQ", GPlusLink = "https://plus.google.com/u/0/117418132983615435247/posts" });
            GrayedData.Add(new GrayedInfo() { ID = 33, Name = "أخبار المصريين", Image = "Assets/AkhbarAlMsrieen.png", WebsiteLink = "http://www.egyptiansnews.com/", FacebookLink = "https://www.facebook.com/blmasri", TwitterLink = "https://twitter.com/blmasry1", GPlusLink = "https://plus.google.com/u/0/116736848332335932150" });
            GrayedData.Add(new GrayedInfo() { ID = 34, Name = "الخميس", Image = "Assets/Alkhamees.png", WebsiteLink = "http://www.elkhamis.com/", FacebookLink = "https://www.facebook.com/elkhamisofficial", TwitterLink = "https://twitter.com/elkhamis_news", YoutubeLink = "https://www.youtube.com/channel/UCmymgarsXDcI1zNS94qlaVA", GPlusLink = "https://plus.google.com/u/0/117660213524377940991/posts", Lat = "31.238313999999946", Long = "30.047523" });
            GrayedData.Add(new GrayedInfo() { ID = 35, Name = "البشاير", Image = "Assets/AlBshayer.png", Email = "info@elbashayer.com", WebsiteLink = "http://www.elbashayeronline.com/", FacebookLink = "https://www.facebook.com/elbashayer", TwitterLink = "https://twitter.com/elbashayer", GPlusLink = "https://plus.google.com/116085449691908704239/posts", InstagramLink = "http://instagram.com/elbashayer?ref=badge" });
            


        }
    }
}
